import { BookingProvider } from '@/lib/book-context';
import './globals.css';
import type { Metadata } from 'next';
import { Button } from '@/components/ui/button';
import { Briefcase, Home, Tag, User } from 'lucide-react';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ zoom: 0.7 }}>
      <BookingProvider>
        <div>
        {children}
      </div>
       {/* Bottom Navigation */}
       <nav className="fixed bottom-0 left-0 right-0 bg-blue-900 text-white ">
        <div className="flex justify-around p-4">
          <Button variant="ghost" className="flex flex-col items-center hover:bg-blue-900 hover:text-blue-500">
            <Link href="/login">
            <User className=" mb-1" />
            <span className="text-xs">لوحة التحكم</span>
            </Link>
          </Button>
          <Button variant="ghost" className="flex flex-col items-center hover:bg-blue-900 hover:text-blue-500">
          <Link href="/booking">
            <Briefcase  className="mb-1" />
            <span className="text-xs">حجوزاتي</span>
            </Link>

          </Button>
          <Button variant="ghost" className="flex flex-col items-center hover:bg-blue-900 hover:text-blue-500">
          <Link href="/offers">
            <Tag className=" mb-1" />
            <span className="text-xs">العروض</span>
            </Link>

          </Button>
          <Button
            variant="ghost"
            className="flex flex-col items-center text-blue-600 hover:bg-blue-900 hover:text-blue-500"
          >
              <Link href="/">
            <Home className=" mb-1" />
            <span className="text-xs text-white">الصفحة الرئيسية</span>
            </Link>
          </Button>
        </div>
      </nav>
      </BookingProvider>
        </body>
    </html>
  );
}
